name: Publish
on: [workflow_dispatch]
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - name: Publish
        run: |
          pip install twine poetry==1.6.1
          poetry build
          poetry publish --username __token__ --password ${{ secrets.PYPI_TOKEN }}
