name: Publish
on: [workflow_dispatch]
jobs:
  publish:
    strategy:
      matrix:
        python-version: ["3.9"]
        poetry-version: ["1.7.1"]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - name: Install poetry
        uses: abatilo/actions-poetry@v2
      - uses: actions/cache@v3
        name: Define a cache for the virtual environment based on the dependencies lock file
        with:
          path: ./.venv
          key: venv-${{ hashFiles('poetry.lock') }}
      - name: Install the project dependencies
        run: |
          poetry install
          poetry build
          poetry publish --username __token__ --password ${{ secrets.PYPI_TOKEN }}
